defaults:
  - models

name: "train"
n_gpu: 1

optimizer_encoder:
  _target_: torch.optim.Adam
  lr: 5e-5

lr_scheduler_encoder:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 1

batch_size: 5

metrics: []

loss:
  _target_: DEGAN.loss.DELoss

data:
  train:
    batch_size: ${batch_size}
    num_workers: 5
    datasets:
      - _target_: DEGAN.datasets.AAHQDataset
        root_path: datasets/aahq-dataset/aligned
  val:
    batch_size: ${batch_size}
    num_workers: 5
    datasets:
      - _target_: DEGAN.datasets.AAHQDataset
        root_path: datasets/aahq-test

trainer: 
  epochs: 100
  save_dir: "saved/"
  save_period: 5
  verbosity: 2
  monitor: "min val_loss"
  early_stop: 100
  visualize: "wandb"
  wandb_project: "degan_project"
  wandb_run_name: "style_space"
  len_epoch: 200
  grad_norm_clip: 20

wandb_key: 91898ab676432e8d5689a2ce4a88f7131dc1e45c